import anthropic
from dotenv import load_dotenv
import requests
import json
from datetime import datetime
import time

load_dotenv()
client = anthropic.Anthropic()

def get_news_id(num):
    """
    Retrieve a list of the top story IDs from Hacker News.

    Args:
        num (int): The number of top story IDs to return.

    Returns:
        list: A list containing the top `num` story IDs from Hacker News.
    """
    url = 'https://hacker-news.firebaseio.com/v0/topstories.json'
    response = requests.get(url = url)
    response.raise_for_status()
    return response.json()[:num]

def get_news(index):
    """
    Retrieve the details of a specific news item from Hacker News by its index (ID).

    Args:
        index (int): The item ID of the news story to retrieve.

    Returns:
        dict: The JSON-decoded details of the news item.
    """
    url = f'https://hacker-news.firebaseio.com/v0/item/{index}.json'
    response = requests.get(url = url)
    response.raise_for_status()
    return response.json()

def get_analys(news):
    """
    Analyze a news item using an AI model and return the result as a JSON-formatted string.

    Args:
        news (str): The content of the news item to be analyzed.

    Returns:
        tuple: A tuple containing:
            - result (str): A JSON object as a string with the analysis output.
            - input_tokens (int): The number of input tokens used by the model.
            - output_tokens (int): The number of output tokens generated by the model.
    """
    response = client.messages.create(
        model = 'claude-haiku-4-5-20251001',
        max_tokens = 1024,
        system = 'You are a news analyst that respond ONLY a valid JSON object. DO NOT explain. DO NOT wrap output in markdown code fences.',
        messages = [{
            'role': 'user',
            'content': f'''<instruction>
            Analyse the given news and respond ONLY a valid JSON object in the given format,DO NOT wrap output in markdown code fences.
            </instruction>
            <news>{news}</news>
            <format>
                {{
                "sentiment": "positive/neutral/negative",
                "key_themes": ["theme1", "theme2"],
                "importance_score": 7,
                "one_line_summary": "..."  
            }}
            </format>
            '''
        },
        {
            'role': 'assistant',
            'content': '{'
        }]
    )
    result = '{' + next(b.text for b in response.content if b.type == "text")
    return result, response.usage.input_tokens, response.usage.output_tokens

def main():  
    newslist = []
    intokens = 0
    outtokens = 0
    fail_count = 0
    # Fetch news with given news_id list with error handling
    try:
        for id in get_news_id(10):
            try:
                news = get_news(id)
            except Exception as e:
                fail_count += 1
                print(f'Error: {e}')
                print('Skipping current news')
                continue
            clean_news = ({
                'title': news.get('title'),
                'url': news.get('url'),
                'score': news.get('score'),
                'source': news.get('by'),
                'time': news.get('time')
            })
            # Error handling with retries
            for i in range(1,4):
                try:
                    response, intok, outtok = get_analys(clean_news)
                    intokens += intok
                    outtokens += outtok
                    break
                except anthropic.AuthenticationError:
                    print('Invalid or missing Anthropic API key in .env file.')
                    return
                except anthropic.RateLimitError:
                    if i == 3:
                        print(f'Attempt {i}: Too many requests')
                    else:
                        print(f'Attempt {i}: Too many requests, retrying in {i}s')
                        time.sleep(i)
                except anthropic.InternalServerError:
                    if i == 3:
                        print(f'Attempt {i}: Server too busy')
                    else:
                        print(f'Attempt {i}: Server too busy, retrying in {i}s')
                        time.sleep(i)
                except anthropic.APIConnectionError:
                    if i == 3:
                        print(f'Attempt {i}: Bad connection')
                    else:
                        print(f'Attempt {i}: Bad connection, retrying in {i}s')
                        time.sleep(i)
                except Exception as e:
                    if i == 3:
                        print(f'Attempt {i}: Unexpected error: {e}')
                    else:
                        print(f'Attempt {i}: Unexpected error: {e}, retrying in {i}s')
                        time.sleep(i)
            else:
                print(f'Max retries reached, news analysis unavailable for news_id: {id}')
                continue

            try:
                data = json.loads(response)
                clean_news.update(data)
                newslist.append(clean_news)
            except Exception as e:
                print(f'Invalid format, news analysis unavailable for news_id: {id}')
                continue
    except Exception as e:
        print(f'Error: {e}')
        print(f'HackerNews API unavailable.')
        return
    # Calculating tokens
    total_cost = (intokens/1000000) * 1.00 + (outtokens/1000000) * 5.00
    print(f'Input tokens: {intokens}, Output tokens: {outtokens}, Estimated cost: ${total_cost:.6f}.')
    # Sort by importance_score
    newslist.sort(reverse = True, key = lambda x: int(x.get('importance_score',0)))  
    # Summary formatting
    current_time = datetime.now().strftime('%Y/%m/%d %H:%M:%S')
    print(f'TOP 10 LATEST NEWS ({current_time}):')
    for index, news in enumerate(newslist,1):
        print(f"{index:<2}) {news.get('title')} ({news.get('sentiment')})")
        print(f"    Summary         : {news.get('one_line_summary')}")
        print(f"    Importance score: {news.get('importance_score')}")
        print(f"    Themes          : {', '.join(news.get('key_themes'))}")
        print(f"    URL             : {news.get('url')}")

if __name__ == '__main__':
    main()